module.exports = {
  // auth
  AUTH_FETCHING: 'AUTH_FETCHING',
  AUTH_SUCCESS: 'AUTH_SUCCESS',
  AUTH_FAILURE: 'AUTH_FAILURE',

  // getFavorites
  GET_FAVORITES_FETCHING: 'GET_FAVORITES_FETCHING',
  GET_FAVORITES_SUCCESS: 'GET_FAVORITES_SUCCESS',
  GET_FAVORITES_FAILURE: 'GET_FAVORITES_FAILURE',

  // downloadFavorites
  DOWNLOAD_FAVORITES_FETCHING: 'DOWNLOAD_FAVORITES_FETCHING',
  DOWNLOAD_FAVORITES_SUCCESS: 'DOWNLOAD_FAVORITES_SUCCESS',
  DOWNLOAD_FAVORITES_FAILURE: 'DOWNLOAD_FAVORITES_FAILURE',
};
