module.exports = {
  // auth
  AUTH_FETCHING: 'AUTH_FETCHING',
  AUTH_SUCCESS: 'AUTH_SUCCESS',
  AUTH_FAILURE: 'AUTH_FAILURE',

  // getPlaylists
  GET_PLAYLISTS_FETCHING: 'GET_PLAYLISTS_FETCHING',
  GET_PLAYLISTS_SUCCESS: 'GET_PLAYLISTS_SUCCESS',
  GET_PLAYLISTS_FAILURE: 'GET_PLAYLISTS_FAILURE',

  // getSongs
  GET_SONGS_FETCHING: 'GET_SONGS_FETCHING',
  GET_SONGS_SUCCESS: 'GET_SONGS_SUCCESS',
  GET_SONGS_FAILURE: 'GET_SONGS_FAILURE',

  // downloadSongs
  DOWNLOAD_SONGS_FETCHING: 'DOWNLOAD_SONGS_FETCHING',
  DOWNLOAD_SONGS_SUCCESS: 'DOWNLOAD_SONGS_SUCCESS',
  DOWNLOAD_SONGS_FAILURE: 'DOWNLOAD_SONGS_FAILURE',
};
